# Generated by Django 4.2.1 on 2023-05-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0004_students_selected_college_students_selected_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='picture',
        ),
        migrations.AddField(
            model_name='students',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='media/'),
        ),
    ]
