# Generated by Django 4.2.1 on 2023-05-21 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0005_remove_students_picture_students_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Studentss',
        ),
    ]
