# Generated by Django 4.2.1 on 2023-05-21 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0006_rename_students_studentss'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studentss',
            new_name='Student',
        ),
    ]
