# Generated by Django 4.2.1 on 2023-05-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0009_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=100, null=True)),
                ('place', models.CharField(max_length=100, null=True)),
                ('pincode', models.CharField(max_length=100, null=True)),
                ('college_strength', models.CharField(max_length=5, null=True)),
                ('inaugration_date', models.DateField()),
                ('naac_grade', models.CharField(max_length=3, null=True)),
                ('principal_phone', models.CharField(max_length=20, null=True)),
                ('alt_phone', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('photo', models.ImageField(default='default.jpg', upload_to='media/')),
            ],
        ),
    ]
