# Generated by Django 4.2.1 on 2023-05-21 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0010_college'),
    ]

    operations = [
        migrations.DeleteModel(
            name='College',
        ),
    ]
