# Generated by Django 4.2.1 on 2023-05-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0012_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='selected_college',
        ),
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.CharField(default='empty', max_length=100),
        ),
    ]
