# Generated by Django 4.1.4 on 2023-06-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissionapp", "0013_remove_student_selected_college_student_college"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="status",
            field=models.CharField(default="0", max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="username",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
