# Generated by Django 4.2.1 on 2023-06-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0014_student_status_student_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('rating', models.CharField(max_length=100, null=True)),
                ('feedback', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
