# Generated by Django 4.2 on 2023-06-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0021_remove_student_status_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(default='notapplied', max_length=50),
        ),
    ]
