# Generated by Django 4.2 on 2023-06-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0024_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='rej',
            field=models.BooleanField(default=False),
        ),
    ]
