# Generated by Django 4.2 on 2023-06-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0025_application_rej'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='college',
            name='courses_available',
            field=models.ManyToManyField(blank=True, to='admissionapp.course'),
        ),
    ]
