# Generated by Django 4.2 on 2023-06-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0026_course_college_courses_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='courses_available',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AddField(
            model_name='college',
            name='courses_available',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
