# Generated by Django 4.2 on 2023-06-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0028_notification_alter_college_courses_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(max_length=100),
        ),
    ]
