# Generated by Django 4.2.1 on 2023-07-02 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0033_remove_college_alt_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='middle_name',
        ),
    ]
