# Generated by Django 4.2.1 on 2023-07-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0034_remove_student_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
