# Generated by Django 4.2.1 on 2023-07-03 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0035_alter_notification_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
