# Generated by Django 4.2 on 2023-07-05 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0037_application_std'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='clg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
